[versions]
kotlinTelegramBot = "6.1.0"
gson = "2.10.1"
okhttpBom = "4.12.0"
retrofit = "2.9.0"
exposedSqlite = "0.46.0"
sqliteJdbc = "3.44.1.0" # DO NOT UPDATE -> CAUSES "ID IS NOT IN THE RECORD" ISSUE

[libraries]
# Kotlin Telegram Bot Library
kotlin-telegram-bot = { module = "io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram", version.ref = "kotlinTelegramBot" }

# Google Gson Library
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }

# Square OkHttp Library
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okhttpBom" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor" }

# Square Retrofit Library
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

# Exposed SQL library
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedSqlite" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedSqlite" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedSqlite" }

# SQLite JDBC Library
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }

[plugins]