package util

object Gifs {
    internal const val COTTON_FARM_FILE_ID = "CgACAgQAAxkBAANfZZ6fI3peqNrZvmxeP_OXbV1DVT0AAl8GAAK1GSBRIB_fe0osYoY0BA"
    internal const val WOMEN_FILE_ID = "CgACAgQAAxkBAANdZZ6dwiCXGI4zHtRqHheMmWhlPt0AAloQAAIxFUFQ58yBz5cnU9A0BA"
    internal const val POOH_AND_CJ_FILE_ID = "CgACAgQAAxkBAANZZZ6c5ydjcfJI9VHCZb9V3RNol3UAAqAEAAJpHGQHyeUWCiOJcY00BA"
    internal const val JOHN_XINA_FILE_ID = "CgACAgQAAxkBAAN5ZZ7Phj_VUxKpx6ICHiqN1OTTg_YAAnEDAALQ7CxQpYm4bk4Vags0BA"
    internal const val EXECUTION_FILE_ID = "CgACAgQAAxkBAAICsmXlkfBM6AzYxSOCNGHhRJsIM0pKAAKkAAM5_vFSKnqFipz6Zoc0BA"
    internal const val REVIVALE_FILE_ID = "CgACAgQAAxkBAAICtWXltRyKPIc3Cwvcw9Bm0yXjX7eyAAJmBgACa7iAUgEWmywkxJ5mNAQ"
}